'use client';

import React, { useState, useEffect } from 'react';
import { useSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { 
  BookOpen, Terminal, CheckCircle, HelpCircle, 
  Send, Brain, Compass, Shield, User, LogOut, Award, ArrowLeft, FileText
} from 'lucide-react';
import confetti from 'canvas-confetti';

// Pre-packaged quiz questions if database is empty
const DEFAULT_QUIZ = {
  title: "Mock Exam: Random Forests Concepts & Coding",
  questions: [
    {
      number: 1,
      section: "Theory",
      type: "MCQ",
      marks: 5,
      question: "Which of the following is true about Gini Impurity in Random Forests?",
      options: [
        "It measures the level of disorder or impurity in a node.",
        "A higher Gini impurity represents a more homogenous node.",
        "It is mathematically equivalent to Entropy.",
        "It ranges from -1 to 1."
      ],
      answer: "It measures the level of disorder or impurity in a node."
    },
    {
      number: 2,
      section: "Theory",
      type: "SAQ",
      marks: 10,
      question: "Explain why Random Forests utilize bagging (bootstrap aggregating).",
      answer: "bagging" // keyword search check
    },
    {
      number: 3,
      section: "Programming",
      type: "Programming",
      marks: 15,
      question: "Write a Python function `gini_impurity(labels: list[int]) -> float` that calculates the Gini Impurity of a list of classification labels.",
      starterCode: "def gini_impurity(labels: list[int]) -> float:\n    # Write your code here\n    pass"
    }
  ]
};

export default function StudentPortal() {
  const { data: session, status } = useSession();
  const router = useRouter();

  // Authentication check
  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/');
    }
  }, [status, router]);

  // Quiz state
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [evaluation, setEvaluation] = useState<any>(null);

  // AI Tutor chat state
  const [chatInput, setChatInput] = useState('');
  const [messages, setMessages] = useState<Array<{ sender: 'user' | 'tutor'; text: string }>>([
    { sender: 'tutor', text: 'Hello! I am your AI doubt solver. Ask me anything about Random Forests, Decision Trees, or Compiler Design, and I will explain it with flashcards!' }
  ]);
  const [tutorLoading, setTutorLoading] = useState(false);

  // Flashcards generated by AI Tutor
  const [flashcards, setFlashcards] = useState<Array<{ front: string; back: string }>>([
    { front: "What is bagging?", back: "Bootstrap Aggregating: training multiple estimators in parallel using bootstrapped datasets to reduce model variance." },
    { front: "Gini Impurity Range", back: "For binary classification, Gini ranges from 0.0 (pure node) to 0.5 (perfectly split node)." }
  ]);

  const handleQuizSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitted(true);

    // Perform auto-evaluation simulation
    let score = 0;
    const feedback: any[] = [];

    // Q1 MCQ
    if (answers[1] === (DEFAULT_QUIZ.questions[0] as any).options?.[0]) {
      score += 5;
      feedback.push({ qNum: 1, correct: true, feedback: "Excellent! Correctly identified that Gini measures disorder." });
    } else {
      feedback.push({ qNum: 1, correct: false, feedback: `Incorrect. The correct answer was option A.` });
    }

    // Q2 SAQ
    const q2Ans = (answers[2] || "").toLowerCase();
    if (q2Ans.includes('bagging') || q2Ans.includes('bootstrap') || q2Ans.includes('variance') || q2Ans.includes('aggregating')) {
      score += 10;
      feedback.push({ qNum: 2, correct: true, feedback: "Perfect! You identified the core bagging properties (bootstrap aggregating & variance reduction)." });
    } else {
      feedback.push({ qNum: 2, correct: false, feedback: "Partially correct. Try to mention bootstrap aggregation, parallel ensembles, or reducing variance." });
    }

    // Q3 Code
    const q3Ans = (answers[3] || "");
    if (q3Ans.includes('for') && q3Ans.includes('impurity') && q3Ans.includes('len')) {
      score += 15;
      feedback.push({ qNum: 3, correct: true, feedback: "Great code logic! Your function passes the standard hidden testcases for classification subsets." });
    } else {
      score += 5; // partial credit
      feedback.push({ qNum: 3, correct: false, feedback: "Logic compiled but missed exact classification output splits. Ensure you calculate label squared probabilities." });
    }

    setEvaluation({
      score,
      total: 30,
      percent: Math.round((score / 30) * 100),
      feedback
    });

    confetti({ particleCount: 100, spread: 60, origin: { y: 0.8 } });
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim()) return;

    const userText = chatInput;
    setMessages((prev) => [...prev, { sender: 'user', text: userText }]);
    setChatInput('');
    setTutorLoading(true);

    // AI Tutor mock response after brief delay
    setTimeout(() => {
      let reply = "";
      let newCard = null;

      const q = userText.toLowerCase();
      if (q.includes('gini') || q.includes('impurity')) {
        reply = "Gini Impurity calculates the likelihood that a randomly selected feature would be misclassified. Mathematically: Gini = 1 - sum(p_i^2). Here is a new study flashcard added!";
        newCard = { front: "Gini Impurity Equation", back: "Gini = 1 - sum(p_i^2) where p_i is probability of class i." };
      } else if (q.includes('bagging') || q.includes('forest')) {
        reply = "Random Forests build hundreds of decision trees using bagging. Bagging trains each tree on random subsets (with replacement). This reduces tree variance without increasing bias. Added a flashcard!";
        newCard = { front: "Why Random Forests use Bagging", back: "It builds independent trees using random samples, reducing ensemble variance." };
      } else {
        reply = "That is a great question! In Machine Learning, keeping a balance between bias and variance is key. When trees grow deep, they have low bias but high variance; combining them resolves this. I have added a flashcard for review.";
        newCard = { front: "Bias-Variance Tradeoff", back: "Bias represents model assumptions simplicity; Variance represents sensitivity to data fluctuations." };
      }

      setMessages((prev) => [...prev, { sender: 'tutor', text: reply }]);
      if (newCard) {
        setFlashcards((prev) => [newCard, ...prev]);
      }
      setTutorLoading(false);
    }, 1000);
  };

  if (status === 'loading') {
    return (
      <div style={{ display: 'flex', height: '100vh', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-primary)' }}>
        <div className="nav-logo-icon" style={{ width: '50px', height: '50px', fontSize: '24px' }}>🤖</div>
      </div>
    );
  }

  return (
    <div className="dashboard-layout" style={{ display: 'grid', gridTemplateColumns: '260px 1fr', minHeight: '100vh', background: 'var(--bg-primary)' }}>
      {/* Sidebar */}
      <aside style={{ background: 'rgba(5, 11, 24, 0.9)', borderRight: '1px solid var(--glass-border)', padding: '24px', display: 'flex', flexDirection: 'column', gap: '32px' }}>
        <div className="nav-logo">
          <div className="nav-logo-icon">🤖</div>
          <span className="nav-logo-text">Auto TA Agent</span>
        </div>

        <nav style={{ display: 'flex', flexDirection: 'column', gap: '8px', flex: 1 }}>
          <button
            onClick={() => router.push('/dashboard')}
            className="sidebar-link"
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              width: '100%',
              padding: '12px 16px',
              borderRadius: '8px',
              border: 'none',
              background: 'transparent',
              color: 'var(--text-secondary)',
              cursor: 'pointer',
              fontWeight: 600,
              fontSize: '0.9rem',
              textAlign: 'left',
            }}
          >
            <Compass size={18} /> Professor Console
          </button>

          <button
            className="sidebar-link active"
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              width: '100%',
              padding: '12px 16px',
              borderRadius: '8px',
              border: 'none',
              background: 'rgba(0, 255, 136, 0.1)',
              color: 'var(--green)',
              cursor: 'pointer',
              fontWeight: 600,
              fontSize: '0.9rem',
              textAlign: 'left',
            }}
          >
            <FileText size={18} /> Student Portal
          </button>
        </nav>

        <div style={{ borderTop: '1px solid var(--glass-border)', paddingTop: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'var(--green-dim)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--green)', border: '1px solid var(--green)' }}>
              <User size={16} />
            </div>
            <div>
              <div style={{ fontSize: '0.8rem', fontWeight: 700, color: '#fff' }}>{session?.user?.name || 'Alice Smith'}</div>
              <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>{(session?.user as any)?.role || 'STUDENT'}</div>
            </div>
          </div>
          <button
            onClick={() => signOut({ callbackUrl: '/' })}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              background: 'transparent',
              border: 'none',
              color: 'var(--pink)',
              fontSize: '0.85rem',
              cursor: 'pointer',
              fontWeight: 600
            }}
          >
            <LogOut size={16} /> Sign Out
          </button>
        </div>
      </aside>

      {/* Main portal grid */}
      <main style={{ padding: '40px', display: 'grid', gridTemplateColumns: '1fr 360px', gap: '32px', maxHeight: '100vh', overflowY: 'auto' }}>
        
        {/* Left Side: Quiz attempt canvas */}
        <div>
          <div style={{ marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <button onClick={() => router.push('/dashboard')} style={{ background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', display: 'flex', alignItems: 'center' }}>
              <ArrowLeft size={18} />
            </button>
            <h2 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#fff' }}>Smart Assessment Engine</h2>
          </div>

          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: 'var(--card-radius-lg)', padding: '32px' }}>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 700, color: '#fff', marginBottom: '8px' }}>{DEFAULT_QUIZ.title}</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', borderBottom: '1px solid var(--glass-border)', paddingBottom: '16px', marginBottom: '24px' }}>
              This quiz is auto-evaluated semantically by the TA Agent grading layer. Take your time.
            </p>

            {!submitted ? (
              <form onSubmit={handleQuizSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
                
                {/* MCQ Question */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, color: 'var(--cyan)' }}>
                    <span>QUESTION 1 (MCQ)</span>
                    <span>[5 Marks]</span>
                  </div>
                  <div style={{ fontSize: '1rem', color: '#fff', fontWeight: 600 }}>{DEFAULT_QUIZ.questions[0].question}</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                    {(DEFAULT_QUIZ.questions[0] as any).options?.map((opt: string) => (
                      <label key={opt} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '12px', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--glass-border)', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem' }}>
                        <input
                          type="radio"
                          name="q1"
                          value={opt}
                          checked={answers[1] === opt}
                          onChange={(e) => setAnswers({ ...answers, 1: e.target.value })}
                          style={{ accentColor: 'var(--green)' }}
                        />
                        {opt}
                      </label>
                    ))}
                  </div>
                </div>

                {/* SAQ Question */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, color: 'var(--cyan)' }}>
                    <span>QUESTION 2 (SAQ)</span>
                    <span>[10 Marks]</span>
                  </div>
                  <div style={{ fontSize: '1rem', color: '#fff', fontWeight: 600 }}>{DEFAULT_QUIZ.questions[1].question}</div>
                  <textarea
                    value={answers[2] || ''}
                    onChange={(e) => setAnswers({ ...answers, 2: e.target.value })}
                    placeholder="Write your explanation here..."
                    required
                    style={{
                      width: '100%',
                      height: '100px',
                      padding: '16px',
                      background: 'rgba(5, 11, 24, 0.8)',
                      border: '1px solid var(--glass-border)',
                      borderRadius: '8px',
                      color: '#fff',
                      fontSize: '0.9rem',
                      resize: 'none'
                    }}
                  />
                </div>

                {/* Code Question */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, color: 'var(--cyan)' }}>
                    <span>QUESTION 3 (PROGRAMMING)</span>
                    <span>[15 Marks]</span>
                  </div>
                  <div style={{ fontSize: '1rem', color: '#fff', fontWeight: 600 }}>{DEFAULT_QUIZ.questions[2].question}</div>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.8rem' }}>
                    <div style={{ background: '#090d16', border: '1px solid var(--glass-border)', borderTopLeftRadius: '8px', borderTopRightRadius: '8px', padding: '10px', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <Terminal size={14} /> main.py (Python IDE)
                    </div>
                    <textarea
                      value={answers[3] || DEFAULT_QUIZ.questions[2].starterCode}
                      onChange={(e) => setAnswers({ ...answers, 3: e.target.value })}
                      style={{
                        width: '100%',
                        height: '180px',
                        padding: '16px',
                        background: '#040710',
                        border: '1px solid var(--glass-border)',
                        borderTop: 'none',
                        borderBottomLeftRadius: '8px',
                        borderBottomRightRadius: '8px',
                        color: '#00ff88',
                        fontFamily: 'var(--font-mono)',
                        fontSize: '0.85rem',
                        resize: 'none'
                      }}
                    />
                  </div>
                </div>

                <button
                  type="submit"
                  className="btn btn-primary"
                  style={{ padding: '14px', borderRadius: '8px', fontWeight: 700, background: 'var(--green)', color: '#050b18' }}
                >
                  Submit Quiz Answers
                </button>
              </form>
            ) : (
              // Quiz Score report
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', padding: '32px 0', borderBottom: '1px solid var(--glass-border)', marginBottom: '24px' }}>
                  <Award size={48} style={{ color: 'var(--green)' }} />
                  <h4 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#fff' }}>Assessment Evaluation Complete</h4>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: '4px' }}>
                    <span style={{ fontSize: '3rem', fontWeight: 800, color: 'var(--green)' }}>{evaluation.score}</span>
                    <span style={{ color: 'var(--text-secondary)' }}>/ {evaluation.total} Marks</span>
                  </div>
                  <span style={{ background: 'rgba(0, 255, 136, 0.1)', color: 'var(--green)', border: '1px solid rgba(0, 255, 136, 0.3)', padding: '6px 16px', borderRadius: '20px', fontSize: '0.8rem', fontWeight: 700 }}>
                    Passing Score ({evaluation.percent}%)
                  </span>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                  {evaluation.feedback.map((f: any) => (
                    <div key={f.qNum} style={{ padding: '16px', background: f.correct ? 'rgba(0, 255, 136, 0.03)' : 'rgba(255, 61, 154, 0.03)', border: f.correct ? '1px solid rgba(0, 255, 136, 0.2)' : '1px solid rgba(255, 61, 154, 0.2)', borderRadius: '8px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 700, color: '#fff', fontSize: '0.9rem', marginBottom: '6px' }}>
                        {f.correct ? <CheckCircle size={16} style={{ color: 'var(--green)' }} /> : <HelpCircle size={16} style={{ color: 'var(--pink)' }} />}
                        Question {f.qNum} Feedback
                      </div>
                      <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{f.feedback}</p>
                    </div>
                  ))}
                </div>

                <button
                  onClick={() => {
                    setSubmitted(false);
                    setAnswers({});
                    setEvaluation(null);
                  }}
                  className="btn btn-outline"
                  style={{ width: '100%', marginTop: '32px', padding: '12px' }}
                >
                  Attempt Quiz Again
                </button>
              </motion.div>
            )}
          </div>
        </div>

        {/* Right Side: AI Tutor doubt solver chat & flashcards */}
        <aside style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {/* Chat box */}
          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: 'var(--card-radius-lg)', padding: '24px', height: '400px', display: 'flex', flexDirection: 'column' }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#fff', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--glass-border)', paddingBottom: '12px', marginBottom: '16px' }}>
              <Brain size={16} style={{ color: 'var(--cyan)' }} /> AI Tutor Doubt Solver
            </h3>

            {/* Messages Area */}
            <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '12px', paddingBottom: '12px', fontSize: '0.8rem' }}>
              {messages.map((m, idx) => (
                <div key={idx} style={{ alignSelf: m.sender === 'user' ? 'flex-end' : 'flex-start', background: m.sender === 'user' ? 'var(--cyan-dim)' : 'rgba(255,255,255,0.03)', border: m.sender === 'user' ? '1px solid var(--cyan)' : '1px solid var(--glass-border)', padding: '10px 14px', borderRadius: '8px', maxWidth: '85%', color: '#fff' }}>
                  {m.text}
                </div>
              ))}
              {tutorLoading && (
                <div style={{ alignSelf: 'flex-start', color: 'var(--text-muted)' }}>Thinking...</div>
              )}
            </div>

            {/* Chat Input form */}
            <form onSubmit={handleSendMessage} style={{ display: 'flex', gap: '8px', borderTop: '1px solid var(--glass-border)', paddingTop: '16px' }}>
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask e.g. 'Explain bagging'"
                style={{
                  flex: 1,
                  padding: '10px 12px',
                  background: 'rgba(5, 11, 24, 0.8)',
                  border: '1px solid var(--glass-border)',
                  borderRadius: '6px',
                  color: '#fff',
                  fontSize: '0.8rem'
                }}
              />
              <button
                type="submit"
                style={{
                  background: 'var(--cyan)',
                  color: '#050b18',
                  border: 'none',
                  borderRadius: '6px',
                  width: '36px',
                  height: '36px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  cursor: 'pointer'
                }}
              >
                <Send size={16} />
              </button>
            </form>
          </div>

          {/* Flashcards block */}
          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--glass-border)', borderRadius: 'var(--card-radius-lg)', padding: '24px' }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#fff', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <BookOpen size={16} style={{ color: 'var(--violet)' }} /> Smart Flashcards
            </h3>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', maxHeight: '250px', overflowY: 'auto' }}>
              {flashcards.map((fc, idx) => (
                <div key={idx} style={{ padding: '12px', background: 'rgba(5,11,24,0.6)', border: '1px solid var(--glass-border)', borderRadius: '8px', fontSize: '0.8rem' }}>
                  <div style={{ fontWeight: 700, color: 'var(--violet)', marginBottom: '4px' }}>Q: {fc.front}</div>
                  <div style={{ color: 'var(--text-secondary)' }}>A: {fc.back}</div>
                </div>
              ))}
            </div>
          </div>
        </aside>
      </main>
    </div>
  );
}
